/**
 * Thin wrapper around `@tauri-apps/plugin-updater` so the rest of the app
 * doesn't have to deal with the plugin's promise + event surface directly.
 *
 * Updates are sourced from the `endpoints` configured in `tauri.conf.json`.
 * For this project that points at the GitHub release `latest.json` manifest
 * generated by `tauri-action` when a signing key is configured in CI.
 */

import { check, type Update } from '@tauri-apps/plugin-updater';
import { relaunch } from '@tauri-apps/plugin-process';

export interface UpdateInfo {
  version: string;
  currentVersion: string;
  date?: string;
  notes?: string;
}

export interface UpdateProgress {
  downloaded: number;
  total: number | null;
}

export type UpdateProgressHandler = (progress: UpdateProgress) => void;

let pending: Update | null = null;

/**
 * Ask the configured endpoint whether a newer version is available.
 *
 * Returns `null` when we're already on the latest version, or when the
 * updater is unconfigured (e.g. no signing key in this build). Throws on
 * actual transport / signature failures so the caller can surface them.
 */
export async function checkForUpdate(): Promise<UpdateInfo | null> {
  const update = await check();
  if (!update) {
    pending = null;
    return null;
  }
  pending = update;
  return {
    version: update.version,
    currentVersion: update.currentVersion,
    date: update.date,
    notes: update.body,
  };
}

/**
 * Download and install the most recently advertised update, then relaunch.
 * Must be called after a successful {@link checkForUpdate}.
 */
export async function installPendingUpdate(onProgress?: UpdateProgressHandler): Promise<void> {
  if (!pending) {
    throw new Error('No pending update — call checkForUpdate() first.');
  }
  let total: number | null = null;
  let downloaded = 0;
  await pending.downloadAndInstall((event) => {
    switch (event.event) {
      case 'Started':
        total = event.data.contentLength ?? null;
        downloaded = 0;
        break;
      case 'Progress':
        downloaded += event.data.chunkLength;
        break;
      case 'Finished':
        downloaded = total ?? downloaded;
        break;
    }
    onProgress?.({ downloaded, total });
  });
  await relaunch();
}
