#!/usr/bin/env python3
"""Bump the project version and run the full quality gate.

Usage:
    python scripts/bump-version.py --major
    python scripts/bump-version.py --minor
    python scripts/bump-version.py --patch

Versioning policy (Semantic Versioning):
    MAJOR — breaking schema, settings, or recipe-format change.
    MINOR — new user-visible functionality.
    PATCH — bug fixes, dependency bumps, doc-only changes, internal refactors.

Version files (must stay in lockstep):
    package.json              -> "version"
    src-tauri/Cargo.toml      -> version =
    src-tauri/tauri.conf.json -> "version"
    src-tauri/Cargo.lock      -> regenerated by cargo update
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

VERSION_FILES = [
    ROOT / "package.json",
    ROOT / "src-tauri/Cargo.toml",
    ROOT / "src-tauri/tauri.conf.json",
]

CARGO_LOCK = ROOT / "src-tauri/Cargo.lock"
CARGO_TOML = ROOT / "src-tauri/Cargo.toml"


def parse_version(version_str: str) -> tuple[int, int, int]:
    """Parse 'X.Y.Z' into (major, minor, patch)."""
    m = re.match(r"^(\d+)\.(\d+)\.(\d+)$", version_str.strip().strip('"'))
    if not m:
        raise ValueError(f"Cannot parse version string: {version_str!r}")
    return int(m.group(1)), int(m.group(2)), int(m.group(3))


def format_version(major: int, minor: int, patch: int) -> str:
    return f"{major}.{minor}.{patch}"


def read_version() -> str:
    """Read the current version from package.json."""
    with open(ROOT / "package.json") as f:
        data = json.load(f)
    return data["version"]


def bump_version(major: int, minor: int, patch: int, level: str) -> str:
    if level == "major":
        major += 1
        minor = 0
        patch = 0
    elif level == "minor":
        minor += 1
        patch = 0
    else:  # patch
        patch += 1
    return format_version(major, minor, patch)


def update_file_json(filepath: Path, new_version: str):
    """Update version in a JSON file (package.json, tauri.conf.json)."""
    with open(filepath) as f:
        content = f.read()

    updated = re.sub(
        r'("version"\s*:\s*)"[^"]+"',
        rf'\1"{new_version}"',
        content,
    )
    if updated == content:
        print(f"  ERROR: No version field found in {filepath.name}", file=sys.stderr)
        sys.exit(1)

    with open(filepath, "w") as f:
        f.write(updated)
    print(f"  Updated {filepath.name}")


def update_file_toml(filepath: Path, new_version: str):
    """Update version in Cargo.toml."""
    with open(filepath) as f:
        content = f.read()

    updated = re.sub(
        r'^(version\s*=\s*)"[^"]+"',
        rf'\1"{new_version}"',
        content,
        flags=re.MULTILINE,
    )
    if updated == content:
        print(f"  ERROR: No version field found in {filepath.name}", file=sys.stderr)
        sys.exit(1)

    with open(filepath, "w") as f:
        f.write(updated)
    print(f"  Updated {filepath.name}")


def update_version_files(old_version: str, new_version: str):
    print(f"\nBumping version: {old_version} -> {new_version}\n")
    print("Updating version files:")

    for fpath in VERSION_FILES:
        if fpath.name == "Cargo.toml":
            update_file_toml(fpath, new_version)
        else:
            update_file_json(fpath, new_version)

    print()


def update_cargo_lock():
    print("Updating Cargo.lock...")
    result = subprocess.run(
        [
            "cargo",
            "update",
            "-p",
            "llama-recipe-manager",
            "--manifest-path",
            str(CARGO_TOML),
        ],
        capture_output=True,
        text=True,
        cwd=str(ROOT / "src-tauri"),
    )
    if result.returncode != 0:
        print(f"  ERROR: cargo update failed:\n{result.stderr}", file=sys.stderr)
        sys.exit(1)
    print("  Cargo.lock updated")
    print()


def run_checks():
    """Run the full quality gate: check, lint, test, format."""
    cmds = [
        ["bun", "run", "check"],
        ["bun", "run", "lint"],
        ["bun", "run", "test"],
        ["bun", "run", "format:check"],
        ["bun", "run", "lint:rust"],
        ["bun", "run", "test:rust"],
        ["bun", "run", "format:rust", "--", "--check"],
    ]

    print("Running full quality gate...\n")
    for cmd in cmds:
        desc = " ".join(cmd[2:])
        print(f"  Running: {' '.join(cmd[1:])} {desc}")
        result = subprocess.run(cmd, cwd=str(ROOT))
        if result.returncode != 0:
            print(f"\n  FAILED: {' '.join(cmd)}", file=sys.stderr)
            print(
                f"\n  Version bump aborted. Fix the failures above, then re-run:\n"
                f"    python scripts/bump-version.py {sys.argv[1] if len(sys.argv) > 1 else '--patch'}",
                file=sys.stderr,
            )
            sys.exit(1)
        print(f"  OK\n")

    print("All checks passed!\n")


def main():
    parser = argparse.ArgumentParser(
        description="Bump project version and run quality gate.",
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--major", action="store_true", help="Bump major version")
    group.add_argument("--minor", action="store_true", help="Bump minor version")
    group.add_argument("--patch", action="store_true", help="Bump patch version")

    args = parser.parse_args()
    level = "major" if args.major else "minor" if args.minor else "patch"

    old_version = read_version()
    major, minor, patch = parse_version(old_version)
    new_version = bump_version(major, minor, patch, level)

    update_version_files(old_version, new_version)
    update_cargo_lock()
    run_checks()

    print(f"Version bump complete: {old_version} -> {new_version}")
    print(f"\nNext steps:")
    print(f"  1. Update the changelog (move Unreleased -> [Unreleased])")
    print(f"  2. Commit and create PR: 'release: v{new_version}'")


if __name__ == "__main__":
    main()
