#!/usr/bin/env python3
"""Regenerate platform-native app icons from a single square source.

Source:  src-tauri/icons/icon.png  (square, ideally >= 1024x1024)

Each platform has different conventions, and getting them right matters
because users see this icon constantly. `tauri icon` produces square,
edge-to-edge PNGs which is correct for Windows / Linux but wrong for
macOS, and it omits a few useful sizes for Linux desktop themes.

What this script does, per platform:

  macOS  (icon.icns)
    Apple HIG (Big Sur+) requires:
      * a "squircle" silhouette — superellipse with exponent ≈ 5,
        not a plain rounded rectangle
      * an 824/1024 safe area — the artwork sits inside a centred
        ~80% square, leaving a transparent margin so the icon has
        the right visual weight in the Dock and room for badges
    We render a full .iconset (16…512 with @2x) and pack it via
    `iconutil`. Without the squircle + inset, a Tauri-default .icns
    looks oversized and "square" next to native macOS apps.

  Windows  (icon.ico)
    Microsoft's desktop-app guidance: one multi-resolution .ico
    containing 16, 24, 32, 48, 64, 128, 256 with PNG-compressed
    entries for >= 256. Edge-to-edge, no mask — the OS draws the
    taskbar / Start treatment itself. The Tauri default already
    covers most of these; we re-emit it here so adding a size or
    swapping the source is a one-command operation.

  Linux  (multiple PNGs)
    freedesktop hicolor theme: square PNGs at 16, 32, 48, 64, 128,
    256, 512. Edge-to-edge with transparent background; desktop
    environments (GNOME, KDE, …) apply their own theming. We write
    them next to the Tauri-managed PNGs and ensure the bundler
    `bundle.icon` array references the new sizes.

iOS and Android assets generated by `tauri icon` are intentionally
left alone — those platforms expect square edge-to-edge sources and
apply masks at the OS level.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ICONS_DIR = ROOT / "src-tauri" / "icons"
SRC = ICONS_DIR / "icon.png"

# ---------- macOS ------------------------------------------------------------

OUT_ICNS = ICONS_DIR / "icon.icns"

# Apple's published safe-area ratio for macOS app icons (824 / 1024).
MACOS_SAFE_AREA_RATIO = 824 / 1024

# Squircle exponent. n=4 is a softer rounded rect, n=5 closely matches
# Apple's macOS icon mask, n=6+ approaches a square. 5.0 is the standard.
MACOS_SUPERELLIPSE_N = 5.0

# Sizes required for a complete macOS .iconset (iconutil expects these
# exact filenames). Includes @2x retina variants.
MACOS_ICONSET_SIZES: list[tuple[int, str]] = [
    (16, "icon_16x16.png"),
    (32, "icon_16x16@2x.png"),
    (32, "icon_32x32.png"),
    (64, "icon_32x32@2x.png"),
    (128, "icon_128x128.png"),
    (256, "icon_128x128@2x.png"),
    (256, "icon_256x256.png"),
    (512, "icon_256x256@2x.png"),
    (512, "icon_512x512.png"),
    (1024, "icon_512x512@2x.png"),
]

# ---------- Windows ----------------------------------------------------------

OUT_ICO = ICONS_DIR / "icon.ico"

# Per Microsoft's "Icons in Win32 desktop apps" guidance — small sizes
# are needed for the Alt-Tab switcher and dialogs, 256 covers HiDPI
# Start menu / Taskbar; 128 fills the gap for 200% scaling at 64.
WINDOWS_ICO_SIZES = [16, 24, 32, 48, 64, 128, 256]

# ---------- Linux ------------------------------------------------------------

# freedesktop hicolor sizes that desktop environments expect to find.
# We mirror these into src-tauri/icons/ as `<size>x<size>.png`. The
# 32 / 64 / 128 / 128@2x files are also written by `tauri icon`; we
# overwrite them so the source of truth is consistent.
LINUX_PNG_SIZES = [16, 32, 48, 64, 128, 256, 512]


# -----------------------------------------------------------------------------


def load_source() -> Image.Image:
    if not SRC.exists():
        sys.exit(f"error: missing source icon at {SRC.relative_to(ROOT)}")
    src = Image.open(SRC).convert("RGBA")
    if src.width != src.height:
        print(
            f"warning: source is {src.width}x{src.height}, expected square; "
            "results may be distorted",
            file=sys.stderr,
        )
    return src


def squircle_mask(size: int) -> Image.Image:
    """Antialiased superellipse alpha mask of the given size.

    Rendered at 2x and downsampled with Lanczos to get smooth edges
    without paying for a full per-pixel float pass at 4096x4096.
    """
    scale = 2
    s = size * scale
    cx = cy = (s - 1) / 2.0
    a = b = s / 2.0
    y, x = np.mgrid[0:s, 0:s].astype(np.float64)
    v = (np.abs((x - cx) / a) ** MACOS_SUPERELLIPSE_N) + (
        np.abs((y - cy) / b) ** MACOS_SUPERELLIPSE_N
    )
    arr = np.where(v <= 1.0, 255, 0).astype(np.uint8)
    return Image.fromarray(arr, "L").resize((size, size), Image.LANCZOS)


def render_macos_tile(src: Image.Image, size: int) -> Image.Image:
    """Inset artwork into the safe area and apply the squircle mask."""
    canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    safe = max(1, round(size * MACOS_SAFE_AREA_RATIO))
    artwork = src.resize((safe, safe), Image.LANCZOS)
    offset = (size - safe) // 2
    canvas.paste(artwork, (offset, offset), artwork)
    mask = squircle_mask(size)
    out = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    out.paste(canvas, (0, 0), mask)
    return out


def render_square_tile(src: Image.Image, size: int) -> Image.Image:
    """Edge-to-edge square render — for Windows .ico and Linux PNGs."""
    return src.resize((size, size), Image.LANCZOS)


def build_macos(src: Image.Image) -> Path:
    iconset = ICONS_DIR / "icon.iconset"
    if iconset.exists():
        shutil.rmtree(iconset)
    iconset.mkdir(parents=True)
    for size, name in MACOS_ICONSET_SIZES:
        render_macos_tile(src, size).save(iconset / name, format="PNG", optimize=True)
    subprocess.run(
        ["iconutil", "-c", "icns", str(iconset), "-o", str(OUT_ICNS)],
        check=True,
    )
    shutil.rmtree(iconset)
    return OUT_ICNS


def build_windows(src: Image.Image) -> Path:
    """Build a multi-resolution .ico with PNG compression for >=256."""
    base = render_square_tile(src, max(WINDOWS_ICO_SIZES))
    sizes = [(s, s) for s in WINDOWS_ICO_SIZES]
    base.save(OUT_ICO, format="ICO", sizes=sizes, bitmap_format="png")
    return OUT_ICO


def build_linux(src: Image.Image) -> list[Path]:
    written: list[Path] = []
    for size in LINUX_PNG_SIZES:
        out = ICONS_DIR / f"{size}x{size}.png"
        render_square_tile(src, size).save(out, format="PNG", optimize=True)
        written.append(out)
    # Tauri also looks for a @2x variant of 128. Keep it in sync.
    out_2x = ICONS_DIR / "128x128@2x.png"
    render_square_tile(src, 256).save(out_2x, format="PNG", optimize=True)
    written.append(out_2x)
    # NOTE: src-tauri/icons/icon.png is intentionally NOT overwritten —
    # it is the human-supplied source of truth that this script reads.
    return written


def build_webview_assets(src: Image.Image) -> list[Path]:
    """Refresh icons consumed by the SvelteKit frontend.

    These files are NOT bundled into the platform installers — they're
    served as static assets to the WebView and used by in-app UI like
    the About dialog. Kept in sync with the source so updating the icon
    only requires re-running this script, no manual copies.
    """
    written: list[Path] = []
    static_icon = ROOT / "static" / "icon.png"
    static_icon.parent.mkdir(parents=True, exist_ok=True)
    render_square_tile(src, 256).save(static_icon, format="PNG", optimize=True)
    written.append(static_icon)
    docs_icon = ROOT / "docs" / "assets" / "icon.png"
    if docs_icon.parent.exists():
        render_square_tile(src, 256).save(docs_icon, format="PNG", optimize=True)
        written.append(docs_icon)
    return written


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    p.add_argument(
        "--platforms",
        nargs="+",
        choices=["macos", "windows", "linux"],
        default=["macos", "windows", "linux"],
        help="subset of platforms to regenerate (default: all)",
    )
    return p.parse_args()


def main() -> int:
    args = parse_args()
    src = load_source()

    if "macos" in args.platforms:
        path = build_macos(src)
        print(f"macos   -> {path.relative_to(ROOT)}")
    if "windows" in args.platforms:
        path = build_windows(src)
        print(f"windows -> {path.relative_to(ROOT)}")
    if "linux" in args.platforms:
        for path in build_linux(src):
            print(f"linux   -> {path.relative_to(ROOT)}")

    # WebView assets (static/, docs/) are always refreshed regardless of
    # platform filter — they're tiny and the README + About dialog should
    # never drift from the bundle icons.
    for path in build_webview_assets(src):
        print(f"webview -> {path.relative_to(ROOT)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
